# Generated by Django 4.1.7 on 2023-05-01 12:39

import customer.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='customer', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('birth_date', models.DateTimeField()),
                ('phone_number', models.CharField(max_length=64, validators=[customer.models.Customer.validate_phone_number])),
                ('identification_number', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='address', serialize=False, to='customer.customer')),
                ('address_text', models.CharField(max_length=1024)),
                ('postal_code', models.CharField(max_length=16)),
            ],
        ),
    ]
